export default {
  "/": [
    {
      text: "开始阅读",
      collapsible: false,
      collapsed: false,
      items: [{ text: "开头", link: "/guide" }],
    },
    {
      text: "📓 算法",
      collapsible: true,
      collapsed: false,
      items: [
        { text: "算法阅读", link: "/算法/index.md" },
        { text: "二分查找", link: "/算法/二分查找-704.md" },
        { text: "反转链表", link: "/算法/反转链表-206.md" },
        { text: "两个数组的交集", link: "/算法/两个数组的交集-349.md" },
        { text: "螺旋矩阵2", link: "/算法/螺旋矩阵2-59.md" },
        { text: "设计链表", link: "/算法/设计链表-707.md" },
        { text: "移除链表元素", link: "/算法/移除链表元素-203.md" },
        { text: "移除元素", link: "/算法/移除元素-27.md" },
        { text: "有效的字母异位词", link: "/算法/有效的字母异位词-242.md" },
        { text: "有序数组的平方", link: "/算法/有序数组的平方-977.md" },
        { text: "长度最小的数组", link: "/算法/长度最小的数组-207.md" },
        { text: "两数之和", link: "/算法/两数之和-1.md" },
        { text: "四数相加2", link: "/算法/四数相加2-454.md" },
        { text: "反转字符", link: "/算法/反转字符-344.md" },
        { text: "js实现数据结构", link: "/算法/js实现数据结构.md" },
        { text: "反转字符串2", link: "/算法/反转字符串2-541.md" },
        { text: "用栈实现队列", link: "/算法/用栈实现队列.md" },
        {
          text: "删除字符串中所有相临重复项",
          link: "/算法/删除字符串中所有相临重复项-1047.md",
        },
        { text: "有效的括号", link: "/算法/有效的括号-20.md" },
        { text: "逆波兰表达式求值", link: "/算法/逆波兰表达式求值-150.md" },
        { text: "二叉树概论", link: "/算法/二叉树概论.md" },
        { text: "二叉树递归遍历", link: "/算法/二叉树递归遍历.md" },
        { text: "二叉树的层序遍历", link: "/算法/二叉树的层序遍历-102.md" },
        { text: "翻转二叉树", link: "/算法/翻转二叉树-226.md" },
        { text: "对称二叉树", link: "/算法/对称二叉树-101.md" },
        { text: "二叉树的最大深度", link: "/算法/二叉树的最大深度-104.md" },
        { text: "二叉树的最小深度", link: "/算法/二叉树的最小深度-111.md" },
        { text: "平衡二叉树", link: "/算法/平衡二叉树-110.md" },
        { text: "完全二叉树的节点个数", link: "/算法/完全二叉树的节点个数-222.md" },
      ],
    },
    {
      text: "📘 JS 学习",
      collapsible: true,
      collapsed: false,
      items: [
        { text: "js阅读", link: "/js/index.md" },
        { text: "单点登录", link: "/js/单点登录.md" },
        {
          text: "如何判断元素是否在可视区域",
          link: "/js/如何判断元素是否在可视区域.md",
        },
        { text: "手写Promise", link: "/js/手写Promise.md" },
        { text: "小知识", link: "/js/小知识.md" },
        { text: "Array方法", link: "/js/Array方法.md" },
        { text: "bind,apply,call", link: "/js/bind,apply,call.md" },
        { text: "ES6对象新增的拓展", link: "/js/ES6对象新增的拓展.md" },
        {
          text: "JavaScript字符串的常用方法有哪些",
          link: "/js/JavaScript字符串的常用方法有哪些.md",
        },
        { text: "js的原型链", link: "/js/js的原型链.md" },
        { text: "let,var,const", link: "/js/let,var,const.md" },
        { text: "js上下文", link: "/js/js上下文.md" },
        { text: "Symbol类型", link: "/js/Symbol类型.md" },
        { text: "type和instanceof", link: "/js/type和instanceof.md" },
        { text: "33个常用js代码", link: "/js/33个常用js代码.md" },
        { text: "常用正则表达式", link: "/js/常用正则表达式.md" },
        { text: "对调变量", link: "/js/对调变量.md" },
        { text: "JQuery", link: "/js/JQuery.md" },
        { text: "promise执行机制", link: "/js/primise的执行机制.md" },
      ],
    },
    {
      text: "📗 java",
      collapsible: true,
      collapsed: false,
      items: [
        { text: "java阅读", link: "/java/index.md" },
        { text: "proxy", link: "/java/Proxy.md" },
        { text: "IO基础", link: "/java/IO基础.md" },
        { text: "IO模型详解", link: "/java/IO模型详解.md" },
        { text: "IO设计模式", link: "/java/IO设计模式.md" },
        { text: "java并发（上）", link: "/java/java并发（上）.md" },
        { text: "项目开发1", link: "/java/项目开发1.md" },
        { text: "BIO和NIO的区别", link: "/java/BIO和NIO的区别.md" },
      ],
    },
    {
      text: "🦁 JUC",
      collapsible: true,
      collapsed: false,
      items: [
        { text: "jvm1", link: "/jvm/jvm1.md" },
        { text: "jvm2", link: "/jvm/jvm2.md" },
        { text: "jvm3", link: "/jvm/jvm3.md" },
      ],
    },
    {
      text: "📗 JVM",
      collapsible: true,
      collapsed: false,
      items: [
        { text: "juc1", link: "/juc/JUC1.md" },
        { text: "juc2", link: "/juc/JUC2.md" },
        { text: "juc3", link: "/juc/JUC3.md" },
        { text: "juc4", link: "/juc/JUC4.md" },
      ],
    },
    {
      text: "📗 python",
      collapsible: true,
      collapsed: false,
      items: [
        { text: "python阅读", link: "/python/index.md" },
        { text: "numpy", link: "/python/numpy.md" },
      ],
    },
    {
      text: "📗 kotlin",
      collapsible: true,
      collapsed: false,
      items: [
        { text: "kotlin阅读", link: "/kotlin/index.md" },
        { text: "kotlin的基本用法", link: "/kotlin/kotlin的基本用法.md" },
      ],
    },
    {
      text: "📗 mysql",
      collapsible: true,
      collapsed: false,
      items: [
        { text: "mysql阅读", link: "/mysql/index.md" },
        { text: "SQL注入", link: "/mysql/SQL注入.md" },
      ],
    },
    {
      text: "📗 netty",
      collapsible: true,
      collapsed: false,
      items: [
        { text: "netty阅读", link: "/Netty/index.md" },
        { text: "Path", link: "/Netty/Path.md" },
        { text: "ByteBuffer", link: "/Netty/ByteBuffer.md" },
        { text: "FileChannel", link: "/Netty/FileChannel.md" },
        { text: "selector", link: "/Netty/selector.md" },
      ],
    },
    {
      text: "📝 react",
      collapsible: true,
      collapsed: false,
      items: [
        { text: "react阅读", link: "/react/index.md" },
        { text: "react的生命周期", link: "/react/react的生命周期.md" },
        { text: "React组件通信", link: "/react/React组件通信.md" },
        { text: "state和props的区别", link: "/react/state和props的区别.md" },
        { text: "react的hook", link: "/react/react的hook.md" },
      ],
    },
    {
      text: "📝 spring+springboot",
      collapsible: true,
      collapsed: false,
      items: [
        { text: "spring阅读", link: "/spring/index.md" },
        { text: "spring的源码实现1", link: "/spring/spring的源码实现1.md" },
      ],
    },
    {
      text: "📗 vue",
      collapsible: true,
      collapsed: false,
      items: [
        { text: "vue阅读", link: "/vue/index.md" },
        { text: "provide和inject", link: "/vue/provide和inject.md" },
        { text: "vue2的组件通信", link: "/vue/vue2的组件通信.md" },
        { text: "vuex", link: "/vue/vuex.md" },
        { text: "vueRouter", link: "/vue/vueRouter.md" },
      ],
    },
    {
      text: "📗 css",
      collapsible: true,
      collapsed: false,
      items: [
        { text: "css阅读", link: "/css/index.md" },
        { text: "gird布局", link: "/css/gird布局.md" },
        { text: "css小知识", link: "/css/css小知识.md" },
        { text: "flex布局", link: "/css/flex布局.md" },
      ],
    },
  ],
  "/green/": [
    {
      text: "🎈代码故事",
      collapsible: true,
      collapsed: false,
      items: [{ text: "阅读须知", link: "/green/ch" }],
    },
  ],
  "/tool/": [
    {
      text: "🎒 常用",
      collapsible: true,
      collapsed: false,
      items: [{ text: "emoji-list", link: "/tool/emoji-list" }],
    },
  ],
  "/essay/": [
    {
      items: [],
    },
  ],
};
